language: en

pipeline:
- name: SpacyNLP
  model: "en_core_web_sm"
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "bert-base-uncased"
- name: DIETClassifier
  epochs: 150
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 150
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1

policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 150

assistant_id: 20250406-104916-adiabatic-gingham

